---
- name: ensure ssl directory exists
  file:
    path: /var/ssl
    state: directory

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /var/ssl/server.key -out /var/ssl/server.crt -extensions v3_ca creates=/var/ssl/server.crt
