FROM resin/rpi-raspbian:jessie

RUN set -x; \
	gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key CCD91D6111A06851 \
	&& gpg -a --export CCD91D6111A06851 | apt-key add - \
	&& echo "deb http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free" > /etc/apt/sources.list.d/mati75.list

RUN set -x; \
	apt-get update && apt-get upgrade; \
	apt-get install -y php7.0 php7.0-fpm php7.0-gd php7.0-mysql php7.0-cli php7.0-common php7.0-curl php7.0-opcache php7.0-json php7.0-intl php7.0-mbstring php7.0-xml; \
	rm -rf /var/lib/apt/lists/*; \
	mkdir -p /run/php

ADD fpm.conf /etc/php/7.0/fpm/php-fpm.conf

EXPOSE 9000

CMD ["php-fpm7.0", "-F"]
